name: deployment
on: 
    push:
     branches:
         - master
    workflow_dispatch:
env: 
     Welcome: "Welcome to git Traning!!!!!!!!!"    
jobs:
    testing:
        runs-on: windows-latest      
        steps:
          - name: testing Envname
            run: write-host $env:Welcome
          - name : check cache folder
            run:  npm config get cache
          - name : initiate install
            run:  npm install          