name: deployment
on: 
    push:
     branches:
         - master
    workflow_dispatch:
env: 
     Welcome: "Welcome to git Traning!!!!!!!!!"    
jobs:
    testing:
        runs-on: windows-latest      
        steps:
          - name: testing Envname
            run: write-host $env:Welcome
          - name : check cache folder1
            run:  npm config get cache
          - name : configure npm cache
            uses: actions/cache@v4
            with:
              path: C:\npm\cache  # Example for NuGet
              key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config') }}
              restore-keys: |
                    nuget-${{ runner.os }}-

          - name : initiate install
            run:  npm install          