name: deployment
on: 
    push:
     branches:
         - master
         - dev
    workflow_dispatch:
jobs:
    testing:
        runs-on: windows-latest
        env: 
            Welcome: "Welcome to git Traning!!!!!!!!!"
        steps:
          - name: testing Envname
            run: write-host $env:Welcome
          - name: create log folder
            run: |
               write-host "${{github.workspace}}"
               new-item  -path ${{github.workspace}} -name "LoG" -itemtype directory
               get-childitem ${{github.workspace}} -recurse
