name: deployment
on: 
    push:
     branches:
         - master
         - dev
    workflow_dispatch:
jobs:
    testing:
        runs-on: windows-latest
        env: 
            Welcome: "Welcome to git Traning!!!!!!!!!"
        steps:
          - name: testing Envname
            run: write-host $env:Welcome
          - name: check repository
            uses: actions/checkout@v4
          - name: create log folder
            run: |
                new-item  -path ${{github.workspace}} -name "LoG" -itemtype directory
                $env:welcome |out-file ${{github.workspace}}\LoG\log.txt 
          - name: upload artifact
            uses: actions/upload-artifact@v4
            with:
                path:    
                  ${{github.workspace}}\LoG
    Deployment:
         needs: testing
         runs-on: windows-latest         
         steps: 
           - name: check repository
             uses: actions/checkout@v4
           - name: "Wecome message"
             run: write-host $env:welcome
           - name: download artifact
             uses: actions/download-artifact@v4
             with: 
                path:  ${{github.workspace}}\LoG
           - name: List folders
             run: get-childitem ${{github.workspace}}\LoG\artifact -recurse

              